FROM node:8.15.0 as builder

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install react-scripts@2.1.5 -g --silent
COPY . /usr/src/app
ENV REACT_APP_DEPLOY_WIZARD_API_SERVER http://deploy-wizard-api:9801
RUN npm run build

# prod build
FROM nginx:1.14.2-alpine
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
