FROM node:8.16.1 as builder

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json yarn.lock /usr/src/app/
RUN npm install --silent
RUN npm install react-scripts@2.1.5 -g --silent
COPY . /usr/src/app
RUN npm run build

# prod build
FROM nginx:1.17.3-alpine
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
