export const SET_APP_DETAILS = "SET_APP_DETAILS";
export const FINALIZE_APP = "FINALIZE_APP";
export const SET_ERROR = "SET_ERROR";
export const DISMISS_ERROR = "DISMISS_ERROR";
export const NEXT_STEP = "NEXT_STEP";
export const SET_VALIDATION_ERRORS = "SET_VALIDATION_ERRORS";
export const CLEAR_VALIDATION_ERROR = "CLEAR_VALIDATION_ERROR";
